In [1]:
#install packages, you can also use pip install -e .
%pip install yfinance
%pip install pandas
%pip install swig
%pip install numpy
%pip install wrds
%pip install pyportfolioopt
%pip install datetime
%pip install requests

#Install finrl library
%pip install git+https://github.com/AI4Finance-Foundation/FinRL.git

Requirement already satisfied: yfinance in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (0.2.58)
Requirement already satisfied: pandas>=1.3.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from yfinance) (2.5.3)
Requirement already satisfied: requests>=2.31 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from yfinance) (2.34.2)
Requirement already satisfied: multitasking>=0.0.7 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from yfinance) (4.11.7)
Requirement already satisfied: pytz>=2022.5 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from yfinance) (2026.3.post1)
Requirement already satisfied: frozendict>=2.3.4 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from yfinance) (3.17.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from yfinance) (4.15.0)
Requirement already satisfied: curl_cffi>=0.7 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from yfinance) (0.16.3)
Requirement already satisfied: soupsieve>=1.6.1 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from curl_cffi>=0.7->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from curl_cffi>=0.7->yfinance) (2026.7.22)
Requirement already satisfied: pycparser in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2026.3)
Requirement already satisfied: six>=1.5 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from requests>=2.31->yfinance) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from requests>=2.31->yfinance) (1.26.20)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: swig in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (4.5.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (2.5.3)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: wrds in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (3.5.0)
Requirement already satisfied: ipython<=9.8.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from wrds) (9.8.0)
Requirement already satisfied: pandas<2.3,>=2.2 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from wrds) (2.2.3)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from wrds) (2.9.12)
Requirement already satisfied: sqlalchemy<2.1,>=2 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from wrds) (2.0.52)
Requirement already satisfied: decorator>=4.3.2 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from ipython<=9.8.0->wrds) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from ipython<=9.8.0->wrds) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from ipython<=9.8.0->wrds) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.5 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from ipython<=9.8.0->wrds) (0.2.2)
Requirement already satisfied: pexpect>4.3 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from ipython<=9.8.0->wrds) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from ipython<=9.8.0->wrds) (3.0.53)
Requirement already satisfied: pygments>=2.11.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from ipython<=9.8.0->wrds) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from ipython<=9.8.0->wrds) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from ipython<=9.8.0->wrds) (5.16.1)
Requirement already satisfied: numpy>=1.26.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from pandas<2.3,>=2.2->wrds) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from pandas<2.3,>=2.2->wrds) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from pandas<2.3,>=2.2->wrds) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from pandas<2.3,>=2.2->wrds) (2026.3)
Requirement already satisfied: wcwidth>=0.1.4 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython<=9.8.0->wrds) (0.8.3)
Requirement already satisfied: greenlet>=1 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from sqlalchemy<2.1,>=2->wrds) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from sqlalchemy<2.1,>=2->wrds) (4.16.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from jedi>=0.18.1->ipython<=9.8.0->wrds) (0.8.7)
Requirement already satisfied: ptyprocess>=0.5 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from pexpect>4.3->ipython<=9.8.0->wrds) (0.7.0)
Requirement already satisfied: six>=1.5 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas<2.3,>=2.2->wrds) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython<=9.8.0->wrds) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython<=9.8.0->wrds) (3.0.2)
Requirement already satisfied: pure-eval in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython<=9.8.0->wrds) (0.2.3)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pyportfolioopt in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (1.6.0)
Requirement already satisfied: cvxpy>=1.1.19 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from pyportfolioopt) (1.9.2)
Requirement already satisfied: numpy<3.0.0,>=1.26.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from pyportfolioopt) (2.5.3)
Requirement already satisfied: pandas<4.0.0,>=1.0.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from pyportfolioopt) (2.2.3)
Requirement already satisfied: scikit-base<0.14.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from pyportfolioopt) (0.13.2)
Requirement already satisfied: scikit-learn>=0.24.1 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from pyportfolioopt) (1.9.0)
Requirement already satisfied: scipy>=1.3.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from pyportfolioopt) (1.18.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from pandas<4.0.0,>=1.0.0->pyportfolioopt) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from pandas<4.0.0,>=1.0.0->pyportfolioopt) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from pandas<4.0.0,>=1.0.0->pyportfolioopt) (2026.3)
Requirement already satisfied: osqp>=1.0.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from cvxpy>=1.1.19->pyportfolioopt) (1.1.3)
Requirement already satisfied: clarabel>=0.5.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from cvxpy>=1.1.19->pyportfolioopt) (0.11.1)
Requirement already satisfied: scs>=3.2.4.post1 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from cvxpy>=1.1.19->pyportfolioopt) (3.3.1)
Requirement already satisfied: highspy>=1.14.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from cvxpy>=1.1.19->pyportfolioopt) (1.15.1)
Requirement already satisfied: qdldl>=0.1.7.post0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from cvxpy>=1.1.19->pyportfolioopt) (0.1.9.post1)
Requirement already satisfied: sparsediffpy<0.4.0,>=0.3.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from cvxpy>=1.1.19->pyportfolioopt) (0.3.0)
Requirement already satisfied: cffi in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from clarabel>=0.5.0->cvxpy>=1.1.19->pyportfolioopt) (2.1.1)
Requirement already satisfied: jinja2 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from osqp>=1.0.0->cvxpy>=1.1.19->pyportfolioopt) (3.1.6)
Requirement already satisfied: setuptools in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from osqp>=1.0.0->cvxpy>=1.1.19->pyportfolioopt) (84.0.0)
Requirement already satisfied: joblib in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from osqp>=1.0.0->cvxpy>=1.1.19->pyportfolioopt) (1.6.0)
Requirement already satisfied: six>=1.5 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas<4.0.0,>=1.0.0->pyportfolioopt) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from scikit-learn>=0.24.1->pyportfolioopt) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from scikit-learn>=0.24.1->pyportfolioopt) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from joblib->osqp>=1.0.0->cvxpy>=1.1.19->pyportfolioopt) (3.1.2)
Requirement already satisfied: pycparser in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from cffi->clarabel>=0.5.0->cvxpy>=1.1.19->pyportfolioopt) (3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from jinja2->osqp>=1.0.0->cvxpy>=1.1.19->pyportfolioopt) (3.0.3)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: datetime in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (6.0)
Requirement already satisfied: zope.interface in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from datetime) (8.6)
Requirement already satisfied: pytz in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from datetime) (2026.3.post1)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: requests in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib64/python3.13/site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from requests) (1.26.20)
Requirement already satisfied: certifi>=2023.5.7 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from requests) (2026.7.22)
Note: you may need to restart the kernel to use updated packages.
Collecting git+https://github.com/AI4Finance-Foundation/FinRL.git
  Cloning https://github.com/AI4Finance-Foundation/FinRL.git to /tmp/pip-req-build-_chng3xo
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/FinRL.git /tmp/pip-req-build-_chng3xo
  Resolved https://github.com/AI4Finance-Foundation/FinRL.git to commit 2334a5fe6d30629157f13c3b0319e1637e15e123
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: alpaca-py<0.38,>=0.37 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from finrl==0.3.8) (0.37.0)
Requirement already satisfied: alpaca-trade-api<4,>=3 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from finrl==0.3.8) (3.2.0)
Requirement already satisfied: ccxt<4,>=3 in /home/timoross/.local/share/hatch/env/virtual/pro-finrl/G16_L85e/pro-finrl/lib/python3.13/site-packages (from finrl==0.3.8) (3.1.60)
Collecting elegantrl @ git+https://github.com/AI4Finance-Foundation/ElegantRL.git (from finrl==0.3.8)
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to /tmp/pip-install-4xxp2x1q/elegantrl_45c24aa20567422aa18525464474196c
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/ElegantRL.git /tmp/pip-install-4xxp2x1q/elegantrl_45c24aa20567422aa18525464474196c
ERROR: Operation cancelled by user
^C
Note: you may need to restart the kernel to use updated packages.

In [2]:
#Import packages

import pandas as pd
import numpy as np 
import datetime
import yfinance as yf 
import requests

from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split
from finrl import config_tickers
from finrl.config import INDICATORS

import itertools

In [3]:
#Generate List of S&P-500 Tickers

# Source - https://stackoverflow.com/a/75845569
# Posted by Asclepius, modified by community. See post 'Timeline' for change history
# Retrieved 2026-09-07, License - CC BY-SA 4.0

def list_slickcharts_sp500() -> pd.DataFrame:
    # Ref: https://stackoverflow.com/a/75845569/
    url = 'https://www.slickcharts.com/sp500'
    user_agent = 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0'  # Default user-agent fails.
    response = requests.get(url, headers={'User-Agent': user_agent})
    return pd.read_html(response.text, match='Symbol', index_col='Symbol')[0]

df = list_slickcharts_sp500() #Schreibt die erstellte Tabelle in einen Datenframe
df.head() #Zeigt die Struktur der Tabelle
print(df.columns.tolist()) #Gibt die Spaltennamen an -> Debugging
tickers = df.index.str.replace(".", "-", regex=False).tolist() # Schreibt die Indizes in eine Liste, sodass nur noch die Ticker da sind
print(tickers) #Gibt die Liste zur Überprüfung aus -> Debugging

['#', 'Company', 'Weight', 'Price', 'Chg', '% Chg']
['NVDA', 'AAPL', 'MSFT', 'AMZN', 'GOOGL', 'GOOG', 'AVGO', 'META', 'TSLA', 'MU', 'BRK-B', 'LLY', 'JPM', 'WMT', 'AMD', 'V', 'JNJ', 'XOM', 'MA', 'INTC', 'ORCL', 'ABBV', 'BAC', 'CSCO', 'PLTR', 'CVX', 'COST', 'LRCX', 'KO', 'CAT', 'MRK', 'AMAT', 'UNH', 'GE', 'MS', 'PG', 'DELL', 'NFLX', 'HD', 'GS', 'PM', 'WFC', 'PANW', 'RTX', 'SNDK', 'GEV', 'ANET', 'KLAC', 'AMGN', 'TXN', 'C', 'TMO', 'IBM', 'AXP', 'LIN', 'CRWD', 'CRM', 'VZ', 'APH', 'MRVL', 'TMUS', 'STX', 'SCHW', 'PEP', 'ABT', 'GILD', 'DE', 'DIS', 'MCD', 'QCOM', 'T', 'ADI', 'NEE', 'BLK', 'UNP', 'WELL', 'WDC', 'BA', 'PFE', 'COP', 'ETN', 'UBER', 'NOW', 'DHR', 'TJX', 'BKNG', 'VRTX', 'BMY', 'NEM', 'COF', 'GLW', 'CB', 'SPGI', 'PLD', 'ISRG', 'PGR', 'CVS', 'PH', 'LMT', 'MDT', 'SBUX', 'SYK', 'MO', 'LOW', 'FTNT', 'ACN', 'BNY', 'ADP', 'HOOD', 'MPC', 'VRT', 'APP', 'ABNB', 'VLO', 'ADBE', 'CEG', 'MCK', 'FCX', 'HWM', 'EQIX', 'BX', 'PSX', 'SO', 'CME', 'USB', 'TT', 'PNC', 'GD', 'KKR', 'CMCSA', 'PWR', 'DUK', 'DASH', 'CSX', 'INTU', 'WMB', 'ICE', 'MRSH', 'ELV', 'JCI', 'MAR', 'HCA', 'WM', 'UPS', 'MMM', 'MNST', 'MCO', 'SLB', 'EMR', 'REGN', 'AMT', 'SHW', 'CDNS', 'CTAS', 'LITE', 'APO', 'ECL', 'MDLZ', 'MSI', 'CMI', 'TRV', 'GM', 'ITW', 'DDOG', 'FDX', 'EOG', 'SNPS', 'TGT', 'CI', 'NSC', 'ROST', 'NOC', 'ORLY', 'RCL', 'WBD', 'CL', 'HLT', 'KMI', 'DLR', 'BSX', 'HPE', 'AON', 'RSG', 'AEP', 'SPG', 'AJG', 'APD', 'HON', 'PCAR', 'ALL', 'TDG', 'COR', 'TFC', 'BKR', 'URI', 'CRH', 'GWW', 'TRGP', 'MET', 'TEL', 'OKE', 'MPWR', 'OXY', 'NUE', 'AFL', 'CTVA', 'F', 'MRNA', 'O', 'D', 'CAH', 'NXPI', 'NKE', 'FAST', 'FIX', 'TER', 'FANG', 'KEYS', 'PSA', 'COHR', 'SRE', 'AME', 'NDAQ', 'CVNA', 'GRMN', 'STT', 'DVN', 'DAL', 'EW', 'ETR', 'HONA', 'VMRK', 'BDX', 'VST', 'FITB', 'XYZ', 'AMP', 'CARR', 'COIN', 'AZO', 'HUM', 'ROK', 'WAB', 'LHX', 'XEL', 'WDAY', 'PYPL', 'CMG', 'VTR', 'EBAY', 'ADSK', 'CIEN', 'EXC', 'VEEV', 'KDP', 'FERG', 'IQV', 'PAYX', 'CBRE', 'A', 'IDXX', 'PRU', 'IBKR', 'AXON', 'MSCI', 'YUM', 'ADM', 'FLEX', 'LYV', 'ROP', 'MCHP', 'WAT', 'TTWO', 'DHI', 'AIG', 'ED', 'ODFL', 'SYY', 'EL', 'HIG', 'PEG', 'MLM', 'NTAP', 'UAL', 'KVUE', 'KR', 'EXPE', 'KMB', 'HSY', 'IRM', 'STLD', 'MTB', 'WEC', 'EQT', 'HBAN', 'RJF', 'NTRS', 'VMC', 'ACGL', 'EME', 'DXCM', 'CNC', 'RMD', 'BIIB', 'JBL', 'CCI', 'CCL', 'ARES', 'PCG', 'ZTS', 'CPRT', 'CBOE', 'GEHC', 'WTW', 'HAL', 'CFG', 'RDDT', 'IR', 'AEE', 'KHC', 'HPQ', 'EXR', 'DG', 'ON', 'LVS', 'DTE', 'ATO', 'TDY', 'FISV', 'CTSH', 'VICI', 'CASY', 'AWK', 'CPAY', 'OTIS', 'FE', 'MTD', 'WSM', 'ES', 'LH', 'PPL', 'VRSN', 'CINF', 'DGX', 'CNP', 'ECHO', 'SMCI', 'SYF', 'DOV', 'RF', 'JBHT', 'INCY', 'WRB', 'Q', 'NRG', 'PPG', 'TPL', 'PFG', 'XYL', 'DLTR', 'DRI', 'EXPD', 'GPN', 'TPR', 'HUBB', 'VRSK', 'ULTA', 'SW', 'WST', 'BRO', 'PHM', 'KEY', 'VLTO', 'TROW', 'CHD', 'BG', 'EXE', 'OMC', 'L', 'FFIV', 'IFF', 'FSLR', 'STE', 'STZ', 'EIX', 'FIS', 'CMS', 'DOW', 'PKG', 'RL', 'AMCR', 'EFX', 'LYB', 'GIS', 'CF', 'FICO', 'LEN', 'SBAC', 'NI', 'SNA', 'IP', 'BR', 'VTRS', 'LUV', 'FDXF', 'CDW', 'GPC', 'BBY', 'EVRG', 'ZBH', 'GEN', 'TSCO', 'CHTR', 'TSN', 'ESS', 'DD', 'NDSN', 'BEN', 'LNT', 'ROL', 'CHRW', 'FTV', 'ZBRA', 'J', 'INVH', 'NVR', 'LDOS', 'WY', 'BALL', 'IEX', 'KIM', 'SOLV', 'PTC', 'AKAM', 'HST', 'APA', 'TYL', 'ALB', 'MAA', 'SWK', 'EG', 'IVZ', 'RVTY', 'MAS', 'DOC', 'AIZ', 'MKC', 'TRMB', 'REG', 'CRL', 'TKO', 'TXT', 'COO', 'LII', 'SJM', 'GL', 'ALLE', 'BAX', 'AVY', 'ERIE', 'FOXA', 'HAS', 'FOX', 'GDDY', 'CSGP', 'BF-B', 'CPT', 'PSKY', 'HRL', 'PNW', 'IT', 'DVA', 'UDR', 'DECK', 'JKHY', 'TECH', 'DPZ', 'ALGN', 'HII', 'CLX', 'LULU', 'SWKS', 'GNRC', 'NWSA', 'BXP', 'FDS', 'AES', 'MGM', 'PODD', 'FRT', 'HSIC', 'UHS', 'APTV', 'PNR', 'WYNN', 'ARE', 'AOS', 'MOS', 'TAP', 'NCLH', 'BLDR', 'TTD', 'NWS']

/tmp/ipykernel_100626/148648598.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(response.text, match='Symbol', index_col='Symbol')[0]

In [4]:
#Debugging
ticker_test = {"AAPL", "MSFT"}

In [5]:
#Setup für den Yahoo Downloader. Zeiträume werden später gesplitet
TRAIN_START_DATE = '2009-01-01'
TRAIN_END_DATE = '2020-09-01' 
TRADE_START_DATE = '2020-09-01' #Eher Test zur Validierung statt Trading
TRADE_END_DATE = '2026-09-07'

In [ ]:
#Daten herunterladen mit dem Yahoodownloader über den gesamten Zeitraum und den 503 Tickersymbolen
df_raw = YahooDownloader(start_date= TRAIN_START_DATE,
                         end_date = TRADE_END_DATE,
                         ticker_list = tickers).fetch_data()

YF deprecation warning: set proxy via new config function: yf.set_config(proxy=proxy)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['JPM']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['WMT']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['AMD']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['V']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['JNJ']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['XOM']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['MA']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['INTC']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ORCL']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ABBV']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['BAC']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['CSCO']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['PLTR']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['CVX']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['COST']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['LRCX']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['KO']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['CAT']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['MRK']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['AMAT']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['UNH']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['GE']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['MS']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['PG']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['DELL']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['NFLX']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['HD']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['GS']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['PM']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['WFC']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['PANW']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['RTX']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['SNDK']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['GEV']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ANET']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['KLAC']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['AMGN']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['TXN']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['C']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['TMO']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['IBM']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['AXP']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['LIN']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['CRWD']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['CRM']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['VZ']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['APH']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['MRVL']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['TMUS']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['STX']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['SCHW']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['PEP']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ABT']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['GILD']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['DE']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['DIS']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['MCD']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['QCOM']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['T']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ADI']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['NEE']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['BLK']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['UNP']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['WELL']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['WDC']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['BA']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['PFE']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['COP']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ETN']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['UBER']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['NOW']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['DHR']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['TJX']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['BKNG']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['VRTX']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['BMY']: DNSError('Failed to perform, curl: (6) Could not resolve host: fc.yahoo.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[*********************100%***********************]  1 of 1 completed


In [7]:
#Daten anssehen
df_raw.head()

Price,date,close,high,low,open,volume,tic,day
0,2009-01-02,10.259194,10.297098,9.798037,9.854891,4236220,A,4
1,2009-01-02,2.714299,2.722974,2.547105,2.568640,746015200,AAPL,4
2,2009-01-02,17.199024,17.292149,16.816896,17.189391,13163193,ABT,4
3,2009-01-02,7.287052,7.395878,7.226829,7.395878,3445200,ACGL,4
4,2009-01-02,24.225481,24.319016,23.412451,23.412451,3787400,ACN,4

In [8]:
#Daten mit technischen Indikatoren erweitern
fe = FeatureEngineer(use_technical_indicator=True, #Berechnung der technischen Indikatoren aktivieren
                     tech_indicator_list = INDICATORS, #Vorgefertigte Liste an Idikatoren übergeben
                     use_vix = True, #Volatilitätsindex aktivieren
                     use_turbulence=True, #Turbulance Index aktivieren
                     user_defined_feature = False) #Usereigene Features aus

semi_processed_data = fe.preprocess_data(df_raw)

Successfully added technical indicators

[*********************100%***********************]  1 of 1 completed

Shape of DataFrame:  (4421, 8)
Successfully added vix
Successfully added turbulence index

In [9]:
semi_processed_data

,date,close,high,low,open,volume,tic,day,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma,vix,turbulence
0,2009-01-02,10.259194,10.297098,9.798037,9.854891,4236220,A,4,0.000000,10.924279,9.941555,100.000000,66.666667,100.000000,10.259194,10.259194,39.189999,0.000000
1,2009-01-02,2.714299,2.722974,2.547105,2.568640,746015200,AAPL,4,0.000000,10.924279,9.941555,100.000000,66.666667,100.000000,2.714299,2.714299,39.189999,0.000000
2,2009-01-02,17.199024,17.292149,16.816896,17.189391,13163193,ABT,4,0.000000,10.924279,9.941555,100.000000,66.666667,100.000000,17.199024,17.199024,39.189999,0.000000
3,2009-01-02,7.287052,7.395878,7.226829,7.395878,3445200,ACGL,4,0.000000,10.924279,9.941555,100.000000,66.666667,100.000000,7.287052,7.287052,39.189999,0.000000
4,2009-01-02,24.225481,24.319016,23.412451,23.412451,3787400,ACN,4,0.000000,10.924279,9.941555,100.000000,66.666667,100.000000,24.225481,24.225481,39.189999,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1829875,2026-07-30,78.230003,80.830002,77.879997,80.830002,7171000,XEL,3,-0.032799,81.965028,77.873972,47.338658,-79.902999,5.874092,79.994334,79.346630,17.090000,1953.076751
1829876,2026-07-30,155.960144,156.764931,153.535839,154.092234,12578100,XOM,3,3.613730,161.032051,132.069075,58.362322,125.514862,27.945883,143.298454,146.328570,17.090000,1953.076751
1829877,2026-07-30,157.000000,166.160004,155.470001,162.000000,3308000,YUM,3,-1.340789,170.427703,140.296296,52.500878,51.448567,33.730248,155.196667,153.325533,17.090000,1953.076751
1829878,2026-07-30,94.959999,96.480003,93.489998,96.169998,2178000,ZBH,3,1.651183,96.574773,85.739228,55.868352,141.172178,21.775728,90.262766,87.471375,17.090000,1953.076751
1829879,2026-07-30,288.570007,292.760010,276.529999,283.079987,759800,ZBRA,3,7.335199,285.396486,249.932513,61.380753,174.167978,20.612390,261.176000,250.993833,17.090000,1953.076751

In [11]:
#DataFrame nach Tag und Ticker sortieren

list_ticker = semi_processed_data["tic"].unique().tolist()
list_date = list(pd.date_range(semi_processed_data['date'].min(),semi_processed_data['date'].max()).astype(str))
combination = list(itertools.product(list_date,list_ticker))

fully_processed_data = pd.DataFrame(combination, columns=["date","tic"]).merge(semi_processed_data,on=["date", "tic"],how="left")
fully_processed_data = fully_processed_data[fully_processed_data['date'].isin(semi_processed_data['date'])]
fully_processed_data = fully_processed_data.sort_values(['date','tic'])

fully_processed_data = fully_processed_data.fillna(0)

fully_processed_data.head()

,date,tic,close,high,low,open,volume,day,macd,boll_ub,boll_lb,rsi_30,cci_30,dx_30,close_30_sma,close_60_sma,vix,turbulence
0,2009-01-02,A,10.259194,10.297098,9.798037,9.854891,4236220.0,4.0,0.0,10.924279,9.941555,100.0,66.666667,100.0,10.259194,10.259194,39.189999,0.0
1,2009-01-02,AAPL,2.714299,2.722974,2.547105,2.568640,746015200.0,4.0,0.0,10.924279,9.941555,100.0,66.666667,100.0,2.714299,2.714299,39.189999,0.0
2,2009-01-02,ABT,17.199024,17.292149,16.816896,17.189391,13163193.0,4.0,0.0,10.924279,9.941555,100.0,66.666667,100.0,17.199024,17.199024,39.189999,0.0
3,2009-01-02,ACGL,7.287052,7.395878,7.226829,7.395878,3445200.0,4.0,0.0,10.924279,9.941555,100.0,66.666667,100.0,7.287052,7.287052,39.189999,0.0
4,2009-01-02,ACN,24.225481,24.319016,23.412451,23.412451,3787400.0,4.0,0.0,10.924279,9.941555,100.0,66.666667,100.0,24.225481,24.225481,39.189999,0.0

In [13]:
#Speicherung der Daten

#Aufteilung in 2 seperate Listen
train = data_split(fully_processed_data, TRAIN_START_DATE, TRAIN_END_DATE)
trade = data_split(fully_processed_data, TRADE_START_DATE, TRADE_END_DATE)
print(len(train))
print(len(trade))

1215504
614376

In [14]:
train.to_csv("../data/train.csv", index=False)
trade.to_csv("../data/trade.csv", index=False)